# Generated by Django 5.1.1 on 2024-10-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
