# Generated by Django 5.1.1 on 2024-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_schedule_description_speaker_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/events/%Y/%m/%d"
            ),
        ),
    ]
