# Generated by Django 5.1.1 on 2024-10-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("caption", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="")),
                ("position", models.IntegerField(default=1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
    ]
