# Generated by Django 5.1.1 on 2024-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_eventimage_delete_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventimage",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
