# Generated by Django 5.1.1 on 2024-11-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_schedule_image_speaker_image_alter_eventimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%Y/%m/%d/events"
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%Y/%m/%d/event_images"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%Y/%m/%d/schedules/"
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%Y/%m/%d/speakers/"
            ),
        ),
    ]
